interface Cmd { f: string; a: string; d: string; invokerType?: string }

  // Fallback hardcoded list — replaced at runtime by /Commands endpoint (if available) when server starts
export const FALLBACK_COMMANDS: Cmd[] = [
    {f:'!account ban',a:'[email]',d:'Bans the specified account.'},
    {f:'!account create',a:'[email] [playerName] [password]',d:'Creates a new account.'},
    {f:'!account download',a:'',d:'Downloads a JSON copy of the current account.'},
    {f:'!account info',a:'',d:'Shows information for the logged in account.'},
    {f:'!account password',a:'[email] [password]',d:'Changes password for the specified account.'},
    {f:'!account playername',a:'[email] [playername]',d:'Changes player name for the specified account.'},
    {f:'!account unban',a:'[email]',d:'Unbans the specified account.'},
    {f:'!account unwhitelist',a:'[email]',d:'Removes the specified account from the whitelist.'},
    {f:'!account userlevel',a:'[email] [0/1/2]',d:'Changes user level for the specified account.'},
    {f:'!account verify',a:'[email] [password]',d:'Checks if an email/password combination is valid.'},
    {f:'!account whitelist',a:'[email]',d:'Whitelists the specified account.'},
    {f:'!achievement info',a:'[id]',d:'Outputs info for the specified achievement.'},
    {f:'!achievement localeid',a:'',d:'Generates a LocaleStringId from the argument.'},
    {f:'!aoi print',a:'',d:'Prints player AOI information to the server console.'},
    {f:'!aoi refs',a:'',d:'Prints interest references for the current player.'},
    {f:'!aoi update',a:'',d:'Forces AOI proximity update.'},
    {f:'!aoi volume',a:'[value]',d:'Changes player AOI volume size.'},
    {f:'!boost damage',a:'[1-10000]',d:'Sets DamagePctBonus for the current avatar.'},
    {f:'!boost invulnerable',a:'',d:'Switches Invulnerable for the current avatar.'},
    {f:'!boost mana',a:'',d:'Switches NoEnduranceCosts for the current avatar.'},
    {f:'!boost vsboss',a:'[1-10000]',d:'Sets DamagePctBonusVsBosses for the current avatar.'},
    {f:'!client info',a:'[sessionId]',d:'Prints information about the specified client.'},
    {f:'!client kick',a:'[playerName]',d:'Disconnects the client with the specified player name.'},
    {f:'!debug ai',a:'',d:'No description available.'},
    {f:'!debug area',a:'',d:'Shows current area.'},
    {f:'!debug cell',a:'',d:'Shows current cell.'},
    {f:'!debug compactloh',a:'',d:'Requests GC to compact the large object heap.'},
    {f:'!debug crashgame',a:'',d:'Crashes the current game instance.'},
    {f:'!debug crashserver',a:'',d:'Crashes the entire server.'},
    {f:'!debug difficulty',a:'',d:'Shows current difficulty level information.'},
    {f:'!debug forcegc',a:'',d:'Requests the garbage collector to perform a collection.'},
    {f:'!debug getconditionlist',a:'',d:'Gets all conditions tracked by the ConditionPool.'},
    {f:'!debug geteventpoolreport',a:'',d:'Returns a report of the ScheduledEventPool state.'},
    {f:'!debug metagame',a:'[on/off]',d:'No description available.'},
    {f:'!debug region',a:'',d:'Shows current region.'},
    {f:'!debug seed',a:'',d:'Shows current seed.'},
    {f:'!debug test',a:'',d:'Runs test code.'},
    {f:'!entity create',a:'[pattern] [count]',d:'Create entity near the avatar based on pattern.'},
    {f:'!entity dummy',a:'[pattern]',d:'Replace the training room dummy with the specified entity.'},
    {f:'!entity info',a:'[EntityId]',d:'Displays information about the specified entity.'},
    {f:'!entity near',a:'[radius]',d:'Displays all entities within a radius (default 100).'},
    {f:'!entity tp',a:'[pattern]',d:'Teleports to the first entity matching the given pattern.'},
    {f:'!instance list',a:'',d:"Lists instances in the player's WorldView."},
    {f:'!instance reset',a:'',d:"Resets private instances in the player's WorldView."},
    {f:'!item cleardeliverybox',a:'',d:'Destroys all items in the delivery box inventory.'},
    {f:'!item creditchest',a:'',d:'Converts credits to a sellable chest item.'},
    {f:'!item destroyindestructible',a:'',d:'Destroys indestructible items from general inventory.'},
    {f:'!item drop',a:'[pattern] [count]',d:'Creates and drops the specified item from the current avatar.'},
    {f:'!item give',a:'[pattern] [count]',d:'Creates and gives the specified item to the current player.'},
    {f:'!item roll',a:'[pattern]',d:'Rolls the specified loot table.'},
    {f:'!item rollall',a:'',d:'Rolls all loot tables.'},
    {f:'!leaderboards all',a:'',d:'Shows all leaderboards.'},
    {f:'!leaderboards enabled',a:'',d:'Shows enabled leaderboards.'},
    {f:'!leaderboards instance',a:'[instanceId]',d:'Shows details for the specified leaderboard instance.'},
    {f:'!leaderboards now',a:'',d:'Shows all active instances.'},
    {f:'!leaderboards reloadschedule',a:'',d:'Reloads leaderboard schedule from JSON.'},
    {f:'!level awardxp',a:'[amount]',d:'Awards the specified amount of experience.'},
    {f:'!level max',a:'',d:"Maxes out the current avatar's experience."},
    {f:'!level maxinfinity',a:'',d:'Maxes out Infinity experience.'},
    {f:'!level maxomega',a:'',d:'Maxes out Omega experience.'},
    {f:'!level reset',a:'',d:'Resets the current avatar to level 1.'},
    {f:'!level resetinfinity',a:'',d:'Removes all Infinity progression.'},
    {f:'!level resetomega',a:'',d:'Removes all Omega progression.'},
    {f:'!level up',a:'',d:'Levels up the current avatar.'},
    {f:'!lookup asset',a:'[pattern]',d:'Searches assets.'},
    {f:'!lookup blueprint',a:'[pattern]',d:'Searches blueprints.'},
    {f:'!lookup costume',a:'[pattern]',d:'Searches prototypes using the costume blueprint.'},
    {f:'!lookup item',a:'[pattern]',d:'Searches prototypes using the item blueprint.'},
    {f:'!lookup power',a:'[pattern]',d:'Searches prototypes using the power blueprint.'},
    {f:'!lookup region',a:'[pattern]',d:'Searches prototypes using the region blueprint.'},
    {f:'!metagame event',a:'[next/stop]',d:'Changes current event. Defaults to stop.'},
    {f:'!mission complete',a:'[pattern]',d:'Complete the given mission.'},
    {f:'!mission completestory',a:'',d:'Set all main story missions to completed.'},
    {f:'!mission info',a:'[pattern]',d:'Display information about the given mission.'},
    {f:'!mission region',a:'',d:'List all mission prototypes in the current region.'},
    {f:'!mission reset',a:'[pattern]',d:'Restart the given mission.'},
    {f:'!mission resetstory',a:'',d:'Reset all main story missions.'},
    {f:'!player clearconditions',a:'',d:'Clears persistent conditions.'},
    {f:'!player costume',a:'[name/reset]',d:'Changes costume for the current avatar.'},
    {f:'!player die',a:'',d:'Kills the current avatar.'},
    {f:'!player givecurrency',a:'[amount]',d:'Gives all currencies.'},
    {f:'!player wipe',a:'[playerName]',d:'Wipes all progress for the current account.'},
    {f:'!power cooldownreset',a:'',d:'Resets all cooldowns and charges.'},
    {f:'!power print',a:'',d:'Prints the power collection for the current avatar.'},
    {f:'!power stealpowers',a:'',d:'Unlocks all stolen powers.'},
    {f:'!region generateallsafe',a:'',d:'Generates all safe regions.'},
    {f:'!region info',a:'',d:'Prints info for the current region.'},
    {f:'!region properties',a:'',d:'Prints properties for the current region.'},
    {f:'!region reload',a:'',d:'Reloads the current region.'},
    {f:'!region warp',a:'[name]',d:'Warps the player to another region.'},
    {f:'!server broadcast',a:'',d:'Broadcasts a notification to all players.'},
    {f:'!server reloadcatalog',a:'',d:'Reloads MTX store catalog.'},
    {f:'!server reloaddashboard',a:'',d:'Reloads the web dashboard.'},
    {f:'!server reloadlivetuning',a:'',d:'Reloads live tuning settings.'},
    {f:'!server shutdown',a:'',d:'Shuts the server down.'},
    {f:'!server status',a:'',d:'Prints server status.'},
    {f:'!store addg',a:'[amount]',d:'Adds the specified number of Gs to this account.'},
    {f:'!store convertes',a:'[amount]',d:'Converts Eternity Splinters to Gs.'},
    {f:'!ultimateprestige activate',a:'',d:'Activates Ultimate Prestige for the current hero.'},
    {f:'!ultimateprestige level',a:'',d:'Prints the current Ultimate Prestige level.'},
    {f:'!unlock chapters',a:'',d:'Unlocks all chapters.'},
    {f:'!unlock waypoints',a:'',d:'Unlocks all waypoints.'},
    {f:'!webapi generatekey',a:'',d:'Generates a new web API key.'},
    {f:'!webapi reloadkeys',a:'',d:'Reloads web API keys.'},
    {f:'!commands',a:'',d:'Lists available commands.'},
    {f:'!dance',a:'',d:'Performs the Dance emote (if available).'},
    {f:'!help',a:'',d:'Help needs no help.'},
    {f:'!jail',a:'',d:'Teleports to East Side: Detention Facility (old).'},
    {f:'!position',a:'',d:'Shows current position.'},
    {f:'!syncmana',a:'',d:'Syncs the current mana value with the server.'},
    {f:'!tower',a:'',d:'Teleports to Avengers Tower (original).'},
    {f:'!tp',a:'x:+offset | x y z',d:'Teleports to position.'},
    {f:'!gc collect',a:'',d:'Forces garbage collection.'},
]